server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:./todo-app.db
    driver-class-name: org.sqlite.JDBC
    username: lyg
    password: 2626


  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aladinassignment.assignment.model


jwt:
  secretKey: